version: 2
sources:
  - name: jaffle_shop
    database: raw
    tables:
      - name: customers
        description: Source table containing all customers
      - name: orders
        description: Source table containing all orders
        
  - name: stripe
    database: raw
    tables:
      - name: payment
        description: Source table containing all payments
        loaded_at_field: _BATCHED_AT

        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}